### ISSUE TITLE
大神 运行demo如下问题

### ISSUE THREAD

**Issue by wuyingtong** [JessYanCoding/MVPArms#110]
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.jessyan.mvparms.demo/me.jessyan.mvparms.demo.mvp.ui.activity.UserActivity}: java.lang.IllegalStateException: Unable to find me.jessyan.mvparms.demo.mvp.model.api.service.UserService,first call injectRetrofitService(UserService) in ConfigModule
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                    Caused by: java.lang.IllegalStateException: Unable to find me.jessyan.mvparms.demo.mvp.model.api.service.UserService,first call injectRetrofitService(UserService) in ConfigModule
                                                       at com.jess.arms.utils.Preconditions.checkState(Preconditions.java:46)
                                                       at com.jess.arms.integration.RepositoryManager.obtainRetrofitService(RepositoryManager.java:69)
                                                       at me.jessyan.mvparms.demo.mvp.model.UserModel.getUsers(UserModel.java:38)
                                                       at me.jessyan.mvparms.demo.mvp.presenter.UserPresenter.requestUsers(UserPresenter.java:82)
                                                       at me.jessyan.mvparms.demo.mvp.ui.activity.UserActivity.initData(UserActivity.java:56)
                                                       at com.jess.arms.base.BaseActivity.onCreate(BaseActivity.java:35)
                                                       at android.app.Activity.performCreate(Activity.java:6303)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                       at java.lang.reflect.Method.invoke(Native Method)

**Comment by wuyingtong** [comment]
ConfigModule 中有registerComponents方法，demo中的GlobalConfiguration没有实现该方法，我是之前clone到本地的，今天更新了，不知道是不是没有更新完全，远程依赖最新的2.1.0

**Comment by JessYanCoding** [comment]
不要紧张哈,目前框架是先提前将新的特性推送到 **master** ,等稳定过后会在推送到远程 jcenter 库,这样可以保证稳定和高频的更新,所以 **jcenter** 的 **2.1.0** 版本,是落后于 **Demo** 和 最新源码的,过几天会更新提交到 **jcenter**

**Comment by wuyingtong** [comment]
噢噢，好的，多谢解答！

**Comment by JessYanCoding** [comment]
@TravelerLq Dagger 的基础规则自己去了解下
