### ISSUE TITLE
ClassNotFoundException 异常

### ISSUE THREAD

**Issue by YinZiHao1994** [JessYanCoding/MVPArms#113]
` E/Parcel: Class not found when unmarshalling: sortType
                                                              java.lang.ClassNotFoundException: sortType
                                                                  at java.lang.Class.classForName(Native Method)
                                                                  at java.lang.Class.forName(Class.java:309)
                                                                  at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
                                                                  at android.os.Parcel.readParcelable(Parcel.java:2245)
                                                                  at com.jess.arms.base.delegate.FragmentDelegateImpl.<init>(FragmentDelegateImpl.java:132)
                                                                  at com.jess.arms.base.delegate.FragmentDelegateImpl$1.createFromParcel(FragmentDelegateImpl.java:141)
                                                                  at com.jess.arms.base.delegate.FragmentDelegateImpl$1.createFromParcel(FragmentDelegateImpl.java:138)
                                                                  at android.os.Parcel.readParcelable(Parcel.java:2252)
                                                                  at android.os.Parcel.readValue(Parcel.java:2152)
                                                                  at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
                                                                  at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                                  at android.os.Bundle.getParcelable(Bundle.java:755)
                                                                  at com.jess.arms.integration.ActivityLifecycle$FragmentLifecycle.fetchFragmentDelegate(ActivityLifecycle.java:285)
                                                                  at com.jess.arms.integration.ActivityLifecycle$FragmentLifecycle.onFragmentAttached(ActivityLifecycle.java:173)
                                                                  at android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentAttached(FragmentManager.java:3144)
                                                                  at android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentAttached(FragmentManager.java:3136)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                  at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2893)
                                                                  at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1294)
                                                                  at android.support.v4.app.Fragment.onCreate(Fragment.java:1265)
                                                                  at com.trello.rxlifecycle2.components.support.RxFragment.onCreate(RxFragment.java:64)
                                                                  at android.support.v4.app.Fragment.performCreate(Fragment.java:2180)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                  at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2893)
                                                                  at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
                                                                  at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:353)
                                                                  at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
                                                                  at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onCreate(RxAppCompatActivity.java:59)
                                                                  at com.jess.arms.base.BaseActivity.onCreate(BaseActivity.java:34)
                                                                  at android.app.Activity.performCreate(Activity.java:6113)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:160)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5372)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "sortType" on path: DexPathList[[zip file "/data/app/com.…… `

**Comment by JessYanCoding** [comment]
版本号

**Comment by YinZiHao1994** [comment]
2.1.0

**Comment by JessYanCoding** [comment]
试试 Multidex

**Comment by SlipperM** [comment]
我也是，也用了Multidex。不过还是概率性出现这样的问题，目前出现的概率大概为0.5%。

报错是android.os.BadParcelableException



场景是 viewpager + fragment

`              Fragment fragment = new Fragment();
                Bundle bundle = new Bundle();
                bundle.putString("img",img);
                bundle.putString("desc",desc);
                fragment.setArguments(bundle);
                return fragment;
`

在Fragment中的initData
`       Bundle arguments = getArguments();
        arguments.setClassLoader(getClass().getClassLoader());
        String desc = arguments.getString("desc");
        String imgs = arguments.getString("img");
`

这些都是最简单的使用方法，但bugly反馈的错跟上面提的一样，通过bundle获取的时候报错，个人感觉可能是FragmentDelegateImpl这个类的构造方法有关，希望大神指点指点
`
 protected FragmentDelegateImpl(Parcel in) {
        this.mFragmentManager = in.readParcelable(FragmentManager.class.getClassLoader());
        this.mFragment = in.readParcelable(Fragment.class.getClassLoader());
        this.iFragment = in.readParcelable(IFragment.class.getClassLoader());
        this.mUnbinder = in.readParcelable(Unbinder.class.getClassLoader());
    }
`

bugly的说法是
`
该异常表示对Parcelable数据进行解组时找不到相关类。
[解决方案]：Parcelable是Android提供的一种对象序列化方法，一般用于对象的网络传输、跨进程通信和本地持久化保存。
1.这种报错有一种原因是与Android的classloader机制有关。Android有两种不同的classloaders：framework classloader和Apk classloader，应用启动时默认的classloader是Apk classloader，可以加载Parcelable解组所需的类。当内存不足时，默认classloader将变为framework classloader，它不知道如何加载自己定义的类，因而会报错。解决方法：在解组数据前，加上bundle.setClassLoader(getClass().getClassLoader())，将恢复Apk classloader方式。
2.序列化类发生变更、分dex包、代码混淆和数据被破坏等原因，也可能会引起该异常。
`

**Comment by JessYanCoding** [comment]
用了第一个解决方案,解决了吗

**Comment by xiaobailong24** [comment]
@SlipperM 方便说一下你的测试机型吗？

**Comment by SlipperM** [comment]
@JessYanCoding 应该是Multidex分Dex包导致的，今天打了一个包，安装到手机里就会出现这个问题，在Android Studio中删掉build目录重新构建后，然后就不报这个错了。

**Comment by JessYanCoding** [comment]
@SlipperM 嗯,你这个低概率出现的问题,还真不好处理,我还没重现过
