### ISSUE TITLE
Android4.4 上运行报错   java.lang.NoClassDefFoundError: com.monstar.bigmanagerforuser.app.GlobalConfiguration$$Lambda$1，但是直接在Android4.4上运行master-demo却不报错！。。。。费解

### ISSUE THREAD

**Issue by lycuit** [JessYanCoding/MVPArms#120]
08-01 19:01:19.274 6639-6639/com.monstar.bigmanagerforuser E/dalvikvm: Could not find class 'timber.log.Timber$DebugTree', referenced from method com.monstar.bigmanagerforuser.app.GlobalConfiguration$3.onCreate
08-01 19:01:19.600 6639-6639/com.monstar.bigmanagerforuser E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.monstar.bigmanagerforuser, PID: 6639
                                                                             java.lang.NoClassDefFoundError: com.monstar.bigmanagerforuser.app.GlobalConfiguration$$Lambda$1
                                                                                 at com.monstar.bigmanagerforuser.app.GlobalConfiguration.applyOptions(GlobalConfiguration.java:83)
                                                                                 at com.jess.arms.base.delegate.AppDelegate.getGlobalConfigModule(AppDelegate.java:126)
                                                                                 at com.jess.arms.base.delegate.AppDelegate.onCreate(AppDelegate.java:65)
                                                                                 at com.jess.arms.base.BaseApplication.onCreate(BaseApplication.java:39)
                                                                                 at com.monstar.bigmanagerforuser.app.WEApplication.onCreate(WEApplication.java:50)
                                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                                 at com.lbe.security.service.core.client.b.x.callApplicationOnCreate(Unknown Source)
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
                                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5332)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by lycuit** [comment]
.终于抢在睡觉前解决了，太爽啦：在2.1.5版本的GlobalConfiguration -> injectAppLifecycle -> attachBaseContext(Context base)里面来处理65k的问题，貌似在api21以下系统不起作用，或者说还有某些问题需要完善。

我的解决方法：
不要直接继承使用 BaseApplication , 而是要直接将 BaseApplication 的代码复制到自定义的 Application 里面去。

**Comment by JessYanCoding** [comment]
https://developer.android.com/studio/build/multidex.html
