### ISSUE TITLE
fragment内嵌fragment，随意滑动几下后，退到后台，程序会崩溃

### ISSUE THREAD

**Issue by f987002856** [JessYanCoding/MVPArms#134]
java.lang.RuntimeException: Unable to pause activity {com.a.b/com.a.b.mvp.ui.activity.MainActivity}: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3064)
                                                                           at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3019)
                                                                           at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2997)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:525)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException
                                                                           at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3773)
                                                                           at android.view.ViewGroup.removeViewAt(ViewGroup.java:3737)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2997)
                                                                           at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:225)
                                                                           at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:448)
                                                                           at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onPause(RxAppCompatActivity.java:81)
                                                                           at android.app.Activity.performPause(Activity.java:5235)
                                                                           at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1233)
                                                                           at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3050)
                                                                           at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3019) 
                                                                           at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2997) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                           at android.os.Looper.loop(Looper.java:137) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:525)

**Comment by JessYanCoding** [comment]
看错误日志,错误原因和框架一点关系都没有吧😅

**Comment by flamenvo** [comment]
我也遇到类似问题  好像是rxlifecycle2原因
