### ISSUE TITLE
JessYan: 提交 Issues 时,请看这里,不满足要求直接 Close

### ISSUE THREAD

**Issue by JessYanCoding** [JessYanCoding/MVPArms#150]
> 沟通交流群: [ ![QQGroup](https://img.shields.io/badge/QQ群-301733278-ff69b4.svg) ](https://shang.qq.com/wpa/qunwpa?idkey=1a5dc5e9b2e40a780522f46877ba243eeb64405d42398643d544d3eec6624917)

1. 遇到问题请自行 **Google**,确认这个 **Issues** 是否已有解决方案
2. 如果 **Google** 没有,请在提问前先查看 [常见 Issues](https://github.com/JessYanCoding/MVPArms/wiki/Issues) 中是否已有该 **Issues**
3. 如果 **常见Issues** 中没有该 **Issues** ,则去 [历史 Issues](https://github.com/JessYanCoding/MVPArms/issues?utf8=✓&q=is%3Aissue%20is%3Aclosed%20)  中查找
4. 如果 **历史 Issues** 中也没有则去 [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) 中翻阅文档确认作者是否已给出相关说明
5. 如果都没有,再选择自己提 **Issues** ,提 **Issues** 时,请确保 **Issues** 符合以下要求,否则直接 **Close** !
* **Issues** 描述必须明确,如果是报错一定要有错误日志
* 不要提与框架无关的 **Issues** ,如怎么优化 **View** 的性能? 怎么使用 **Retrofit**？ 
* 如果是与自己项目业务或逻辑有关的 **Issues** ,先确认在官方最新的 **Demo** 上是否会出现相应问题,如果 **Demo** 也会出现,请在 **Issues** 中说明,否则请自己解决
* 本框架基本没有封装与 **UI** 有关的任何封装,所以如果想提与 **UI** 有关的 **Issues** ,请仔细商酌

**Comment by kinghom** [comment]
demo运行后就出现内存泄漏了

**Comment by JessYanCoding** [comment]
@kinghom 这里不能评论

**Comment by fandazeng** [comment]
该框架怎样解决P层复用接口过多的问题？

**Comment by JessYanCoding** [comment]
@fandazeng http://www.jianshu.com/p/ac51c9b88af3

**Comment by kinghom** [comment]
权限申请，申请摄像头的时候，一直调用onRequestPermissionFailureWithAskNeverAgain这方法
我看到备注“用户拒绝了权限请求并且用户选择了以后不再询问, 权限请求失败, 这时将不能继续请求该权限, 需要提示用户进入设置页面打开该权限”
但是实质上没有弹出dialog 选择是否打开允许权限

**Comment by ZengCS** [comment]
01-14 11:32:05.539 29929-29961/me.jessyan.mvparms.demo W/System.err:     at me.jessyan.mvparms.demo.app.GlobalHttpHandlerImpl.onHttpResultResponse(GlobalHttpHandlerImpl.java:66)
01-14 11:32:05.539 29929-29961/me.jessyan.mvparms.demo W/System.err:     at com.jess.arms.http.log.RequestInterceptor.intercept(RequestInterceptor.java:144)
01-14 11:32:05.539 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-14 11:32:05.539 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
01-14 11:32:05.539 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-14 11:32:05.539 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-14 11:32:05.540 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-14 11:32:05.541 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-14 11:32:05.541 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-14 11:32:05.541 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-14 11:32:05.541 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
01-14 11:32:05.541 29929-29961/me.jessyan.mvparms.demo W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
01-14 11:32:05.541 29929-29961/me.jessyan.mvparms.demo W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
01-14 11:32:05.556 29929-29929/me.jessyan.mvparms.demo W/System.err: 	retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden
01-14 11:32:05.559 29929-29929/me.jessyan.mvparms.demo W/System.err: 	Caused by: retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden

**Comment by 1325679717** [comment]
fragment和activity能用一个presenter吗？
