### ISSUE TITLE
proguard error resources-release-stripped.ap_'  specified for property 'resourceFile' does not exist

### ISSUE THREAD

**Issue by jp1017** [JessYanCoding/MVPArms#19]
```
/MVPArms-master/app/build/intermediates/res/resources-release-stripped.ap_' 
specified for property 'resourceFile' does not exist.
```

**Comment by jp1017** [comment]
要打开混淆,,,

```
        release {
            minifyEnabled true
        }
```

**Comment by jp1017** [comment]
运行后报错:

>Process: me.jessyan.mvparms.demo, PID: 4077
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                                           at me.jessyan.mvparms.demo.mvp.b.b.a.a(Unknown Source)
                                                                           at me.jessyan.mvparms.demo.mvp.ui.holder.UserItemHolder.a(Unknown Source)
                                                                           at me.jessyan.mvparms.demo.mvp.ui.holder.UserItemHolder.a(Unknown Source)
                                                                           at com.jess.arms.a.f.a(Unknown Source)
                                                                           at com.jess.arms.a.f.onBindViewHolder(Unknown Source)
                                                                           at com.paginate.a.e.onBindViewHolder(Unknown Source)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(Unknown Source)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(Unknown Source)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)
                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(Unknown Source)
                                                                           at android.support.v7.widget.GridLayoutManager.layoutChunk(Unknown Source)
                                                                           at android.support.v7.widget.LinearLayoutManager.fill(Unknown Source)
                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(Unknown Source)
                                                                           at android.support.v7.widget.GridLayoutManager.onLayoutChildren(Unknown Source)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(Unknown Source)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(Unknown Source)
                                                                           at android.support.v7.widget.RecyclerView.onLayout(Unknown Source)
                                                                           at android.view.View.layout(View.java:15912)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                           at android.support.v4.widget.SwipeRefreshLayout.onLayout(Unknown Source)
                                                                           at android.view.View.layout(View.java:15912)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:633)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:568)
                                                                           at android.view.View.layout(View.java:15912)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                           at android.view.View.layout(View.java:15912)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:633)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:568)
                                                                           at com.zhy.autolayout.AutoFrameLayout.onLayout(Unknown Source)
                                                                           at android.view.View.layout(View.java:15912)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                           at com.zhy.autolayout.AutoLinearLayout.onLayout(Unknown Source)
                                                                           at android.view.View.layout(View.java:15912)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:633)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:568)
                                                                           at android.view.View.layout(View.java:15912)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2467)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2159)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1284)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6495)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:605)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:574)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
                                                                           at android.os.Handler.handleCallback(Handler.java:815)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                           at android.os.Looper.loop(Looper.java:194)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                                           at java.lang.reflect.Method.invoke(Native Method)


感觉是鸿神的库混淆没做好？

**Comment by JessYanCoding** [comment]
这个不清楚...

**Comment by jp1017** [comment]
再帮我分析下哈,

混淆里加了代码行数显示
>-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable

然后是User获取链接空指针,这样修改了：

>-if (avatar_url.isEmpty()) return avatar_url;
+if (TextUtils.isEmpty(avatar_url)) return avatar_url;

运行后，下面这个异常:

>url is required

代码:

public GlideImageConfig build() {
            if (url == null) throw new IllegalStateException("url is required");
            if (imageView == null) throw new IllegalStateException("imageview is required");
            return new GlideImageConfig(this);
}

还会是哪里问题呢？

**Comment by jp1017** [comment]
获取到的json为 `[]`

后面就没的玩了，什么导致的呢，debug下可以

**Comment by jp1017** [comment]
搞定了, 实体类不要混淆：
加入这个：

> #实体类不参与混淆
-keep class me.jessyan.mvparms.demo.mvp.model.entity.** {*;}

**Comment by jp1017** [comment]
:+1: @JessYanCoding 哈哈，昨夜想到是这个问题，还真是 :smile:

**Comment by JessYanCoding** [comment]
我只想说,只要不是第一次做混淆的,都知道,javabean和自定义view不能混淆
