### ISSUE TITLE
Unable to find ConfigModule implementation

### ISSUE THREAD

**Issue by YinZiHao1994** [JessYanCoding/MVPArms#195]
部分机型 已知三星 note3（android4.4.1） 、华为畅玩4X（android4.4.4）出现 Unable to find ConfigModule implementation 问题，打开应用就崩溃

### Bug Log:
```
java.lang.RuntimeException: Unable to instantiate application com.jess.arms.base.BaseApplication: java.lang.IllegalArgumentException: Unable to find ConfigModule implementation
                                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:525)
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)
                                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:141)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: java.lang.IllegalArgumentException: Unable to find ConfigModule implementation
                                                                               at com.jess.arms.integration.ManifestParser.parseModule(ManifestParser.java:68)
                                                                               at com.jess.arms.integration.ManifestParser.parse(ManifestParser.java:52)
                                                                               at com.jess.arms.base.delegate.AppDelegate.<init>(AppDelegate.java:70)
                                                                               at com.jess.arms.base.BaseApplication.attachBaseContext(BaseApplication.java:50)
                                                                               at android.app.Application.attach(Application.java:200)
                                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:976)
                                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:520)
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605) 
                                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:141) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:136) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.ClassNotFoundException: com.qicareful.qi.youjiavr.GlobalConfiguration
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.Class.forName(Class.java:251)
                                                                               at java.lang.Class.forName(Class.java:216)
                                                                               at com.jess.arms.integration.ManifestParser.parseModule(ManifestParser.java:66)
                                                                               at com.jess.arms.integration.ManifestParser.parse(ManifestParser.java:52) 
                                                                               at com.jess.arms.base.delegate.AppDelegate.<init>(AppDelegate.java:70) 
                                                                               at com.jess.arms.base.BaseApplication.attachBaseContext(BaseApplication.java:50) 
                                                                               at android.app.Application.attach(Application.java:200) 
                                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
                                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
                                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:520) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605) 
                                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:141) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:136) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.NoClassDefFoundError: com/qicareful/qi/youjiavr/GlobalConfiguration
                                                                               at java.lang.Class.classForName(Native Method) 
                                                                               at java.lang.Class.forName(Class.java:251) 
                                                                               at java.lang.Class.forName(Class.java:216) 
                                                                               at com.jess.arms.integration.ManifestParser.parseModule(ManifestParser.java:66) 
                                                                               at com.jess.arms.integration.ManifestParser.parse(ManifestParser.java:52) 
                                                                               at com.jess.arms.base.delegate.AppDelegate.<init>(AppDelegate.java:70) 
                                                                               at com.jess.arms.base.BaseApplication.attachBaseContext(BaseApplication.java:50) 
                                                                               at android.app.Application.attach(Application.java:200) 
                                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
                                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
                                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:520) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605) 
                                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:141) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:136) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qicareful.qi.youjiavr.GlobalConfiguration" on path: DexPathList[[zip file "/data/app/com.qicareful.qi.youjiavr-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.qicareful.qi.youjiavr-1, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                               at java.lang.Class.classForName(Native Method) 
                                                                               at java.lang.Class.forName(Class.java:251) 
                                                                               at java.lang.Class.forName(Class.java:216) 
                                                                               at com.jess.arms.integration.ManifestParser.parseModule(ManifestParser.java:66) 
                                                                               at com.jess.arms.integration.ManifestParser.parse(ManifestParser.java:52) 
                                                                               at com.jess.arms.base.delegate.AppDelegate.<init>(AppDelegate.java:70) 
                                                                               at com.jess.arms.base.BaseApplication.attachBaseContext(BaseApplication.java:50) 
                                                                               at android.app.Application.attach(Application.java:200) 
                                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
                                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
                                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:520) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605) 
                                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:141) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:136) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 

```

**Comment by Sum41forever** [comment]
看了下，感觉像是分包导致的，dex文件找不到，然后报错。

**Comment by JessYanCoding** [comment]
麻烦认真看下,  常用 Issues, https://github.com/JessYanCoding/MVPArms/wiki/Issues#3, 下次再出现重复 Issues 不提示直接 Close

**Comment by MartinDong** [comment]
别开枪，自己人，我找到了一个新的快捷的解决方案，直接在 GlobalConfiguration.java 上面添加 @Keep 注解，可以达到同样的解决效果，望采纳。

**Comment by JessYanCoding** [comment]
@MartinDong 贴下代码

**Comment by MartinDong** [comment]
@Keep
public final class GlobalConfiguration implements ConfigModule {

**Comment by JessYanCoding** [comment]
@MartinDong 对 support-annotations 应该没有版本要求吧

**Comment by MartinDong** [comment]
这是个com.android.support，我用的都是一致的

**Comment by JessYanCoding** [comment]
@MartinDong 我还试过, 不知道可行不, 不过还是给你了个引导 https://github.com/JessYanCoding/MVPArms/wiki/Issues#3

**Comment by JessYanCoding** [comment]
@MartinDong 我试了，无效

**Comment by yuandonghua** [comment]
android studio 3.3 我试了各位大神推荐的方案，5.0以上的，5.0一下的方案等等，我都试了，还是不可以，希望大神们试试Android studio 3.3

**Comment by yuandonghua** [comment]
最后我把其他的各种配置全去掉，然后只配置@Keep,解决了问题，minSdkVersion=21

**Comment by Mrzhangsss** [comment]
@YinZiHao1994   我的情况也是这样 刚配置完 一运行就报Unable to find ConfigModule implementation

**Comment by addappcn** [comment]
5.0上没有问题  4以下 上面解决办法都不行  请问怎么解决

**Comment by 932707629** [comment]
+@keep搞定  还是不懂为什么  明明混淆文件已经加了keep class 了

**Comment by zuiaidasde** [comment]
> 5.0上没有问题 4以下 上面解决办法都不行 请问怎么解决
你最后解决了吗？
