### ISSUE TITLE
项目demo运行时，就报了Glide的抽象方法问题

### ISSUE THREAD

**Issue by zzq5636243** [JessYanCoding/MVPArms#198]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log
Process: me.jessyan.mvparms.demo, PID: 20104
java.lang.AbstractMethodError: abstract method "com.bumptech.glide.RequestManager com.bumptech.glide.manager.RequestManagerRetriever$RequestManagerFactory.build(com.bumptech.glide.Glide, com.bumptech.glide.manager.Lifecycle, com.bumptech.glide.manager.RequestManagerTreeNode, android.content.Context)"
at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:390)
at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:132)
at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:114)
at com.bumptech.glide.Glide.with(Glide.java:697)
at com.jess.arms.http.imageloader.glide.GlideArms.with(GlideArms.java:88)
at com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.loadImage(GlideImageLoaderStrategy.java:61)
at com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.loadImage(GlideImageLoaderStrategy.java:49)
at com.jess.arms.http.imageloader.ImageLoader.loadImage(ImageLoader.java:53)
at me.jessyan.mvparms.demo.mvp.ui.holder.UserItemHolder.setData(UserItemHolder.java:64)
at me.jessyan.mvparms.demo.mvp.ui.holder.UserItemHolder.setData(UserItemHolder.java:42)
at com.jess.arms.base.DefaultAdapter.onBindViewHolder(DefaultAdapter.java:74)
at com.jess.arms.base.DefaultAdapter.onBindViewHolder(DefaultAdapter.java:34)
at com.paginate.recycler.WrapperAdapter.onBindViewHolder(WrapperAdapter.java:33)
at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
at android.view.View.layout(View.java:17548)
at android.view.ViewGroup.layout(ViewGroup.java:5614)
at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
at android.view.View.layout(View.java:17548)
at android.view.ViewGroup.layout(ViewGroup.java:5614)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at com.zhy.autolayout.AutoLinearLayout.onLayout(AutoLinearLayout.java:50)
at android.view.View.layout(View.java:17548)
at android.view.ViewGroup.layout(ViewGroup.java:5614)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:17548)
at android.view.ViewGroup.layout(ViewGroup.java:5614)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17548)
at android.view.ViewGroup.layout(ViewGroup.java:5614)

```

### Others:
配置上并没有什么问题，

**Comment by JessYanCoding** [comment]
你确定 Demo 一行代码都没改? 这是 **Glide v4.0** 生成源码没有成功, 或者生成成功后, 没有找到该文件

**Comment by zzq5636243** [comment]
这个只要是没有改Glide的注解那块，就没有问题啊

**Comment by JessYanCoding** [comment]
如果是仓库里的未经修改的源代码, 直接运行报错, 我是会修复的, 如果你改了任何一行代码(你改的代码是否真的和报错无关, 这个谁都不敢确定), 导致的错误, 并且报错是其他三方库, 那就请自行解决

**Comment by zzq5636243** [comment]
我刚从新下了一个新的，一样是报了这个问题

**Comment by JessYanCoding** [comment]
建议你给 Glide 提 Issues, 这个问题我运行并没有问题, 也就不能重现,而且报错也和 Arms 无关

**Comment by etenel** [comment]
这个是mvparms里面已经实现了GlideConfiguration。
GlideModule(glideName = "GlideArms")
public class GlideConfiguration extends AppGlideModule 

你又在demo里面写了一个这个。glide暂时只能有一个这样的module。
而且默认的GlideApp名字改成了GlideArms。。。

**Comment by JessYanCoding** [comment]
AppGlideModule 框架已经提供了，的确不能再一次声明另一个 AppGlideModule 实现类，只有 LibraryGlideModule 能存在多个，但是框架提供了 GlideAppliesOptions 接口，实现这个接口即可拥有和 AppGlideModule 同样的方法

**Comment by mny459** [comment]
请问这个要实现跳过https还在图片要怎么配置，这个时候用的okhttpClient和其他的网络请求不是同一个

**Comment by mny459** [comment]
> @mny459 百度 okhttpClient 如何跳过 https

抱歉，我没有表达清楚。具体需求是这样的，在业务中有两类https请求：
1.  通用的业务请求，需要进行证书验证；
2.  图片加载请求，需要跳过证书验证；

本来想自定义`GlideModule`，发现 框架中已经定义了一个而且配置了`Glide`使用`okhttp` 
[地址](https://github.com/JessYanCoding/MVPArms/blob/HEAD/arms/src/main/java/com/jess/arms/http/imageloader/glide/GlideConfiguration.java)
源码

```java
    @Override
    public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        //Glide 默认使用 HttpURLConnection 做网络请求,在这切换成 Okhttp 请求
        AppComponent appComponent = ArmsUtils.obtainAppComponentFromContext(context);
        registry.replace(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(appComponent.okHttpClient()));
    }
````

`Glide` 似乎在工程中只支持定义一个`GlideModule`，所以我定义的导致了在打正式包时编译不通过，所以才有了以上问题。

框架通过`BaseImageLoaderStrategy` 实现了`applyOptions`方法的可配置，可是锁住了`registerComponents `。

**Comment by JessYanCoding** [comment]
@mny459 registerComponents 是 LibraryGlideModule 的方法，不是 AppGlideModule 的方法，上面我已经提到了 LibraryGlideModule 可以声明多个，你在 第二个 LibraryGlideModule  registry.replace 切换另一个网络框架，自然可以把上一个替换掉

**Comment by YubiwaStar** [comment]
我 声明了LibraryGlideModule  但是并没有执行类中的方法。有人成功过吗。

**Comment by Leu-Z** [comment]
@YubiwaStar @mny459   哥们，你们后来是怎么解决的？我实现了LibraryGlideModule来修改okhttpClient 的后，这个LibraryGlideModule并没有被Glide使用。

**Comment by zzq5636243** [comment]
就是Glide的版本不对，你得改下Glide的版本






------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 下午4:42
收件人: "JessYanCoding/MVPArms"<MVPArms@noreply.github.com>;
抄送: "ノ全球公敵。"<306559652@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [JessYanCoding/MVPArms] 项目demo运行时，就报了Glide的抽象方法问题 (#198)




@YubiwaStar @mny459   哥们，你们后来是怎么解决的？我实现了LibraryGlideModule来修改okhttpClient 的后，这个LibraryGlideModule并没有被Glide使用。

**Comment by Leu-Z** [comment]
@zzq5636243 我把Glide4.0以上的版本全都试了个遍，都不行。请问你用的哪个版本可以？
