### ISSUE TITLE
ImageLoader使用时出现崩溃问题或内存泄露问题

### ISSUE THREAD

**Issue by linmomo** [JessYanCoding/MVPArms#207]
### Environment
- MVPArms Version: 2.4.1
- AndroidStudio Version:3.1.2
- Gradle Plugin Version: 3.1.2
- Target Android Version:27
-  Device Model: MI 5
-  DGlide Version:4.6.1

### Bug Description:
感谢作者作者的贡献，框架非常好用，项目中使用碰到一些问题，请教一下，已经查看过日常问题和检索过问题，如果疏漏，还请见谅。
在Activity通过Inject注入ImageLoader加载图片，使用的实现是作者在框架中默认的glide实现策略，图片加载显示正常，问题出在退出页面的时候，参照作者demo的写法，在onDestroy中进行clear操作，如果使用页面当前的context对象，会造成buglog前半段的异常退出，如果使用ApplicationContext对象，LeakCanary 中会报内存泄露问题，日志已经贴在buglog后半段，不知道是使用方法不对，还是其它问题，检索的时候网上说需要进行onPause处理，但是我看作者的demo中没出现这个情况，以前使用的时候没碰到这样的问题，谢谢指教。

### Related Code:
```java
   @Inject
    ImageLoader mImageLoader;
      mImageLoader.
      
     loadImage(this
     ,ImageConfigImpl.builder()
         .url(userInfo.getAvatarUrl())
                .imageView(mIvHead)
                .isCircle(true)
                .build());

    @Override
    protected void onDestroy() {
        mImageLoader.clear(this, ImageConfigImpl.builder()
                .imageViews(mIvHead)
                .build());
        super.onDestroy();
        this.mImageLoader = null;
    }


```

### Bug Log:
```log
     Caused by: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
        at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:312)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:131)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:115)
        at com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.clear(GlideImageLoaderStrategy.java:150)
        at com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.clear(GlideImageLoaderStrategy.java:56)
        at com.jess.arms.http.imageloader.ImageLoader.clear(ImageLoader.java:64)
        at com.heijing.fives.mvp.ui.activity.OrderDetailActivity.onDestroy(OrderDetailActivity.java:188)
        at android.app.Activity.performDestroy(Activity.java:7208)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 


LeakCanary 日志
06-02 13:29:21.208 19066-19612/com.heijing.fives:leakcanary D/LeakCanary: In com.heijing.fives:1.0.0:1.
    * com.heijing.fives.mvp.ui.activity.OrderDetailActivity has leaked:
    * GC ROOT com.autonavi.ae.gmap.GLMapEngine.mContext
    * references com.heijing.fives.app.MyApplication.mAppDelegate
    * references com.jess.arms.base.delegate.AppDelegate.mAppComponent
    * references com.jess.arms.di.component.DaggerAppComponent.provideImageLoaderStrategyProvider
    * references dagger.internal.DoubleCheck.instance
    * references com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.requests
    * references com.jess.arms.http.imageloader.glide.GlideRequests.context
    * leaks com.heijing.fives.mvp.ui.activity.OrderDetailActivity instance
06-02 13:29:21.209 19066-19612/com.heijing.fives:leakcanary D/LeakCanary: * Retaining: 3.2千字节.
    * Reference Key: eceef281-d869-46e0-b7ba-8fb23bd5c0a5
    * Device: Xiaomi Xiaomi MI 5 gemini
    * Android Version: 8.1.0 API: 27 LeakCanary: 1.5.4 74837f0
    * Durations: watch=5024ms, gc=203ms, heap dump=2482ms, analysis=60912ms
    * Details:
    * Instance of com.autonavi.ae.gmap.GLMapEngine

```

**Comment by JessYanCoding** [comment]
你好, 第一段报错, 是 **Glide** 抛出的, 原因也说明了, 它不允许 **Activity** 在 **Destroy** 中执行你所做的操作

我不知道你为什么需要在 **Destroy** 中做 **clean** 的操作, **Glide.with()** 传入当前 **Activity** 它便可自行处理声明周期, 希望你再认真了解下关于 **Glide** 的一些特性

**Comment by linmomo** [comment]
@JessYanCoding 谢谢你的回答，我在Destroy 中做clear操作是参考你的demo中在Activity的onDestroy 中的操作DefaultAdapter.releaseAllHolder(mRecyclerView)，最后也是调用ViewHolder中的 onRelease方法，里面也进行了claer操作，可能是我没表述清楚，我是在做的时候发现如果我没有进行释放操作，该页面一直会有glide内存泄露的问题，改到onPause中和使用applicationcontex对象来进行clear都还是会有内存泄露问题，我一直没有处理掉，所以才冒昧跟你请教。

**Comment by JessYanCoding** [comment]
我可能是因为 **Holder** 没拿到当前 **Activity** 的引用, 才主动使用 **Application** 做的 **clean**, 至于你的情况我没遇到过, 只要传入当前 **Activity**, **Glide** 会自己启动一个隐形的 **Fragment** 帮你管理生命周期

**Comment by JessYanCoding** [comment]
如果你有兴趣可以找到这个 **Fragment** 打上断点看看, 对你学习上也有帮助, 至于这个 **Fragment** 的类名, 框架会在 **log** 中打印所有 **Fragment** 所执行的生命周期, 你观察下就可以知道

**Comment by linmomo** [comment]
好的，谢谢你的帮助
