### ISSUE TITLE
应用签名打包后一点开就报IllegalArgumentException: Unable to find ConfigModule implementation

### ISSUE THREAD

**Issue by yedona** [JessYanCoding/MVPArms#215]
Process: com.isoftstone.jinhurenshe, PID: 6563
    java.lang.RuntimeException: Unable to instantiate application com.isoftstone.jinhurenshe.JHRSApplication: java.lang.IllegalArgumentException: Unable to find ConfigModule implementation
        at android.app.LoadedApk.makeApplication(LoadedApk.java:578)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.IllegalArgumentException: Unable to find ConfigModule implementation
        at me.jessyan.art.c.j.a(ManifestParser.java:68)
        at me.jessyan.art.c.j.a(ManifestParser.java:52)
        at me.jessyan.art.base.a.c.<init>(AppDelegate.java:70)
        at me.jessyan.art.base.BaseApplication.attachBaseContext(BaseApplication.java:52)
        at android.app.Application.attach(Application.java:187)
        at android.app.Instrumentation.newApplication(Instrumentation.java:997)
        at android.app.Instrumentation.newApplication(Instrumentation.java:981)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.ClassNotFoundException: com.isoftstone.jinhurenshe.app.GlobalConfiguration
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at java.lang.Class.forName(Class.java:285)
        at me.jessyan.art.c.j.a(ManifestParser.java:66)
        at me.jessyan.art.c.j.a(ManifestParser.java:52) 
        at me.jessyan.art.base.a.c.<init>(AppDelegate.java:70) 
        at me.jessyan.art.base.BaseApplication.attachBaseContext(BaseApplication.java:52) 
        at android.app.Application.attach(Application.java:187) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:981) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:573) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.isoftstone.jinhurenshe.app.GlobalConfiguration" on path: DexPathList[[zip file "/data/app/com.isoftstone.jinhurenshe-1/base.apk"],nativeLibraryDirectories=[/data/app/com.isoftstone.jinhurenshe-1/lib/x86, /data/app/com.isoftstone.jinhurenshe-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:324) 
        at java.lang.Class.forName(Class.java:285) 
        at me.jessyan.art.c.j.a(ManifestParser.java:66) 
        at me.jessyan.art.c.j.a(ManifestParser.java:52) 
        at me.jessyan.art.base.a.c.<init>(AppDelegate.java:70) 
        at me.jessyan.art.base.BaseApplication.attachBaseContext(BaseApplication.java:52) 
        at android.app.Application.attach(Application.java:187) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:981) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:573) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: com.isoftstone.jinhurenshe.app.GlobalConfiguration
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 21 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

public class JHRSApplication extends BaseApplication {

    @Override
    public void onCreate() {
        super.onCreate();
        JPushInterface.init(this);
 
    

        //初始化数据库
        CacheDBHelper.init(this);
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        IntentDataHolder.getInstance().removeALLTag();
    }
}

**Comment by JessYanCoding** [comment]
你混淆了, 不要混淆 ConfigModule implementation
