### ISSUE TITLE
ImageConfigImpl.Builder 的 imageViews()无法使用

### ISSUE THREAD

**Issue by YinZiHao1994** [JessYanCoding/MVPArms#244]
- [x] MVPArms Version: 2.4.1

### Related Code:
```
  imageLoader.loadImage(context, ImageConfigImpl.builder()
                    .errorPic(R.drawable.svg_error_image)
                    .url(imageUrl)
                    .imageViews(imageView,imageBackground)
                    .build());

```

### Bug Log:
```log
java.lang.NullPointerException: Imageview is required
        at com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.loadImage(GlideImageLoaderStrategy.java:57)
        at com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.loadImage(GlideImageLoaderStrategy.java:50)
        at com.jess.arms.http.imageloader.ImageLoader.loadImage(ImageLoader.java:53)

```

### Others:
```
        if (config.getImageView() == null) throw new NullPointerException("Imageview is required");
```
框架里这句话只检查了 ImageConfig 中的 imageView是不是为空，而 imageViews() 方法的参数传到ImageView[] imageViews 去了。

**Comment by JessYanCoding** [comment]
ImageLoader.loadImage 本来就不支持加载多个 ImagerView，ImageView[] 是给 ImageLoader.clear 用的
