### ISSUE TITLE
GlobalHttpHandler 重新请求获取token后返回新的response后报错

### ISSUE THREAD

**Issue by 13186137845** [JessYanCoding/MVPArms#263]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
   public GlobalHttpHandlerImpl(Context context) {
        this.context = context;
    }

    /**
     * 这里可以先客户端一步拿到每一次 Http 请求的结果, 可以先解析成 Json, 再做一些操作, 如检测到 token 过期后
     * 重新请求 token, 并重新执行请求
     *
     * @param httpResult 服务器返回的结果 (已被框架自动转换为字符串)
     * @param chain {@link okhttp3.Interceptor.Chain}
     * @param response {@link Response}
     * @return
     */
    @Override
    public Response onHttpResultResponse(@Nullable String httpResult, @NonNull Interceptor.Chain chain, @NonNull Response response) {
        if (!TextUtils.isEmpty(httpResult)) {
            if( RequestInterceptor.isJson(response.body().contentType())){
                return  response;
            }

            if(RequestInterceptor.isText(response.body().contentType())&&httpResult.contains("会话超时或未登录")){
                AppComponent appComponent = ArmsUtils.obtainAppComponentFromContext(Quick.getApplicationContext());
                okhttp3.OkHttpClient.Builder ClientBuilder=new okhttp3.OkHttpClient.Builder();
                ClientBuilder.readTimeout(20, TimeUnit.SECONDS);//读取超时
                ClientBuilder.connectTimeout(6, TimeUnit.SECONDS);//连接超时
                ClientBuilder.writeTimeout(60, TimeUnit.SECONDS);//写入超时
                ClientBuilder.cookieJar(new MyCookiesManager());
                String params = "?userName="+HttpClientHelper.getUserName()+"&&password="+HttpClientHelper.getPassword();
                Request request = new Request
                        .Builder()
                        .url(SharedPreUtils.getInstance().getBaseUrl()+HttpMethodContains.LOGIN_QUERY_URL+params)
                        .method("GET", null)
                        .build();
                try {
                   Response newResponse =   ClientBuilder.build().newCall(request).execute();
                   JSONObject result = JSONObject.parseObject( newResponse.body().string());
                    Quick.withConfigure(ConfigKeys.TOKEN,result.getString("chcToken"));
                    Request newRequest = chain.request().newBuilder()
                            .build();
                    response.body().close();
                    return   ClientBuilder.build().newCall(newRequest).execute();

                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

        }

```

### Bug Log:
```log
W/System.err: java.lang.IllegalArgumentException: networkResponse.networkResponse != null
        at okhttp3.Response$Builder.checkSupportResponse(Response.java:406)
        at okhttp3.Response$Builder.networkResponse(Response.java:391)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err:     at me.jessyan.retrofiturlmanager.RetrofitUrlManager$1.intercept(RetrofitUrlManager.java:136)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.jess.arms.di.module.ClientModule$1.intercept(ClientModule.java:113)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12090)


```

### Others:
最后网络返回了结果，把最后请求到的新Response返回去的时候报错！

**Comment by JessYanCoding** [comment]
okhttp 或 Retrofit 的问题请自行解决 https://github.com/JessYanCoding/MVPArms/issues/150

**Comment by 13186137845** [comment]
这个除了 return new Response.Builder()
                                .code(200)
                                .addHeader("Content-Type", "application/json")
                                .body(ResponseBody.create(MediaType.parse("application/json"),response.body().string()))
                                .message("OK")
                                .request(chain.request())
                                .protocol(Protocol.HTTP_1_1)
                                .build();
还有什么更好的办法吗

**Comment by JessYanCoding** [comment]
试试自己 addInterceptor 在里面看能否返回原有的 Response，很久之前，有人问过我类似问题，我只是大概记得，也不能确定，至于其他办法我也不清楚，很久没写业务了
