### ISSUE TITLE
MultiDex.install(base);初始化的位置问题

### ISSUE THREAD

**Issue by FlogFly** [JessYanCoding/MVPArms#264]
Application初始化时候通过代理，给了AppDelegate来处理，然后通过ManifestParser去加载用户写的各个ConfiModule,然后你在其中的GlobalConfiguration这个ConfigModule中的injectAppLifecycle方法去加了自己的APP生命周期监听，然后调用了MultiDex.install(base);初始化。

但是现在我们小组在开发过程中，有些组员在运行时候就会报错，那就是你在第一步AppDelegate中通过ManifestParser去解析生成ConfigModule对象的时候，就说找不到这个ConfigModule类，不在分包中。因为这时候你都没有初始化MultiDex.install(base);。

```
    Caused by: java.lang.ClassNotFoundException: Didn't find class "aaaa.bbbbb.debug.MaintenanceConfigModuleDebug" on path: DexPathList[[zip file "/data/app/ecarx.maintenance-2.apk"],nativeLibraryDirectories=[/data/app-lib/aaa.maintenance-2, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:251) 
        at java.lang.Class.forName(Class.java:216) 
        at 
```

**Comment by JessYanCoding** [comment]
在 4.4 会出现这个问题，我在 [常见 issues](https://github.com/JessYanCoding/MVPArms/wiki/Issues#3) 中已经给了解决方案
