### ISSUE TITLE
Glide Bad Request图片加载失败

### ISSUE THREAD

**Issue by Participanta** [JessYanCoding/MVPArms#284]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Bug Description:
图片加载失败返回400，bad request

### Related Code:
```java
  Glideconfigration文件registerComponents方法替换okhttp使用的是全局的okhttpclient，当全局okhttpclient配置token等一些参数时导致加载图片失败，返回400错误，建议不要直接使用全局的okhttpclient。

```

### Bug Log:
```log
                                                                     java.io.IOException: Request failed 400: Bad Request
                                                                         at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:90)
                                                                         at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
                                                                         at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)
                                                                         at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
                                                                         at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                                                         at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                                         at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                                         at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
                                                                         at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

```

**Comment by JessYanCoding** [comment]
你如果不想用全局 okhttpclient，可以直接替换回来，这里没有限制你替换任何网络框架

**Comment by JessYanCoding** [comment]
而且服务器返回 400，是因为你自己 [请求服务器传的数据没有对](http://www.cnblogs.com/beppezhang/p/5824986.html)，和是否使用 okhttpclient 没有任何关系
