### ISSUE TITLE
请教一个混淆问题

### ISSUE THREAD

**Issue by PiPiCaptain** [JessYanCoding/MVPArms#286]
- [x] MVPArms Version: 2.5.0
- [x] AndroidStudio Version: 3.3.1
- [x] Target Android Version: 28

开启了混淆，也添加了混淆规则。但混淆报错了，研究了很久，实在不清楚是啥情况。顺便说明一下，项目使用了组件化，组件化也是作者提供的那个方案。BaseActivity和BaseFragment，是我自己另外写的，没用框架里的。

### Bug Log:
Caused by: java.io.IOException: Duplicate jar entry [com/xx/commonsdk/core/BaseActivity_MembersInjector.class]
	at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:155)
	at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:120)
	at proguard.io.JarWriter.createOutputStream(JarWriter.java:137)
	at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:111)
	at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:111)
	at proguard.io.ClassDataEntryWriter.createOutputStream(ClassDataEntryWriter.java:93)
	at proguard.io.ExtraDataEntryWriter.createOutputStream(ExtraDataEntryWriter.java:135)
	at proguard.io.IdleRewriter.read(IdleRewriter.java:49)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.JarReader.read(JarReader.java:83)
	at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
	at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
	at proguard.InputReader.readInput(InputReader.java:210)

**Comment by PiPiCaptain** [comment]
Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: com.eenet.commonsdk.core.BaseActivity_MembersInjector
	at com.android.tools.r8.utils.ProgramClassCollection.resolveClassConflictImpl(ProgramClassCollection.java:64)
	at com.android.tools.r8.utils.ProgramClassCollection.lambda$create$0(ProgramClassCollection.java:25)
	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
	at com.android.tools.r8.utils.ProgramClassCollection.create(ProgramClassCollection.java:24)
	at com.android.tools.r8.graph.LazyLoadedDexApplication$Builder.build(LazyLoadedDexApplication.java:124)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:123)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
	at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:40)
	at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:110)
	at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:83)

**Comment by JessYanCoding** [comment]
在检查一下，有业务代码的混淆方案，还是需要你自己配置，我估计也帮不了啥子忙

**Comment by a1265137718** [comment]
我也遇到了这种问题 有解决吗

**Comment by lee-mou** [comment]
@a1265137718 @PiPiCaptain 在你的 [com/xx/commonsdk]的 build.gradle文件下添加下面一句话就好了 annotationProcessor 'com.google.dagger:dagger-compiler:2.x'

**Comment by bailandi** [comment]
> annotationProcessor 'com.google.dagger:dagger-compiler:xx.xx'

nice老铁 加了之后APT生成的文件就在commonSDK目录下了
