### ISSUE TITLE
部分手机突然出现crach

### ISSUE THREAD

**Issue by xilost** [JessYanCoding/MVPArms#314]
- [x] MVPArms Version: v2.5.0
- [x] AndroidStudio Version: v3.4.1
- [x] Gradle Plugin Version: v5.1.1
- [x] Target Android Version: 28
- [x] Device Model: Redmi Note 5A

crash日志如下：

java.lang.NoClassDefFoundError: java.lang.invoke.SerializedLambda
	at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
	at java.lang.Class.getDexCacheType(Class.java:2551)
	at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
	at java.lang.reflect.Method.getParameterTypes(Method.java:193)
	at java.lang.Class.getDeclaredMethods(Class.java:1812)
	at org.simple.eventbus.SubsciberMethodHunter.findSubcribeMethods(SubsciberMethodHunter.java:69)
	at org.simple.eventbus.EventBus.register(EventBus.java:145)
	at com.jess.arms.integration.EventBusManager.register(EventBusManager.java:58)
	at com.jess.arms.base.delegate.ActivityDelegateImpl.onCreate(ActivityDelegateImpl.java:50)
	at com.jess.arms.integration.ActivityLifecycle.onActivityCreated(ActivityLifecycle.java:91)
	at android.app.Application.dispatchActivityCreated(Application.java:199)
	at android.app.Activity.onCreate(Activity.java:1002)
	at android.support.v4.app.SupportActivity.onCreate(ComponentActivity.java:75)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:335)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
	at com.jess.arms.base.BaseActivity.onCreate(BaseActivity.java:91)
	at android.app.Activity.performCreate(Activity.java:6858)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2710)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2818)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.ClassNotFoundException: Didn&#39;t find class &quot;java.lang.invoke.SerializedLambda&quot; on path: DexPathList[[zip file &quot;/data/app/com.zhidian.teacher-2/base.apk&quot;],nativeLibraryDirectories=[/data/app/com.zhidian.teacher-2/lib/arm64, /data/app/com.zhidian.teacher-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
	... 27 more
java.lang.ClassNotFoundException: Didn&#39;t find class &quot;java.lang.invoke.SerializedLambda&quot; on path: DexPathList[[zip file &quot;/data/app/com.zhidian.teacher-2/base.apk&quot;],nativeLibraryDirectories=[/data/app/com.zhidian.teacher-2/lib/arm64, /data/app/com.zhidian.teacher-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
	at java.lang.Class.getDexCacheType(Class.java:2551)
	at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
	at java.lang.reflect.Method.getParameterTypes(Method.java:193)
	at java.lang.Class.getDeclaredMethods(Class.java:1812)
	at org.simple.eventbus.SubsciberMethodHunter.findSubcribeMethods(SubsciberMethodHunter.java:69)
	at org.simple.eventbus.EventBus.register(EventBus.java:145)
	at com.jess.arms.integration.EventBusManager.register(EventBusManager.java:58)
	at com.jess.arms.base.delegate.ActivityDelegateImpl.onCreate(ActivityDelegateImpl.java:50)
	at com.jess.arms.integration.ActivityLifecycle.onActivityCreated(ActivityLifecycle.java:91)
	at android.app.Application.dispatchActivityCreated(Application.java:199)
	at android.app.Activity.onCreate(Activity.java:1002)
	at android.support.v4.app.SupportActivity.onCreate(ComponentActivity.java:75)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:335)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
	at com.jess.arms.base.BaseActivity.onCreate(BaseActivity.java:91)
	at android.app.Activity.performCreate(Activity.java:6858)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2710)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2818)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by liuchengjian** [comment]
我也遇到了，debug包没啥问题，打正式包就出现打开就崩溃，
也了分包继承MultiDexApplication，也没用，
提示类似的代码：
java.lang.RuntimeException: Unable to instantiate application com.dqgb.gylyth.MainApplication: java.lang.IllegalArgumentException: Unable to find ConfigModule implementation
        at android.app.LoadedApk.makeApplication(LoadedApk.java:807)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5469)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
     Caused by: java.lang.IllegalArgumentException: Unable to find ConfigModule implementation
        at me.jessyan.art.d.i.a(Unknown Source)
        at me.jessyan.art.d.i.a(Unknown Source)
        at me.jessyan.art.a.a.c.<init>(Unknown Source)
        at com.dqgb.gylyth.a.attachBaseContext(Unknown Source)
        at android.app.Application.attach(Application.java:202)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1015)
        at android.app.Instrumentation.newApplication(Instrumentation.java:999)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:801)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5469) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6211) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793) 
     Caused by: java.lang.ClassNotFoundException: com.dqgb.gylyth.app.GlobalConfiguration
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at me.jessyan.art.d.i.a(Unknown Source) 
        at me.jessyan.art.d.i.a(Unknown Source) 
        at me.jessyan.art.a.a.c.<init>(Unknown Source) 
        at com.dqgb.gylyth.a.attachBaseContext(Unknown Source) 
        at android.app.Application.attach(Application.java:202) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1015) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:999) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:801) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5469) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6211) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dqgb.gylyth.app.GlobalConfiguration" on path: DexPathList[[zip file "/data/app/com.dqgb.gylyth-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dqgb.gylyth-1/lib/arm, /data/app/com.dqgb.gylyth-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at java.lang.Class.forName(Class.java:326) 
        at me.jessyan.art.d.i.a(Unknown Source) 
        at me.jessyan.art.d.i.a(Unknown Source) 
        at me.jessyan.art.a.a.c.<init>(Unknown Source) 
        at com.dqgb.gylyth.a.attachBaseContext(Unknown Source) 
        at android.app.Application.attach(Application.java:202) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1015) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:999) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:801) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5469) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6211) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793) 
2019-07-26 12:48:34.796 3198-3198/? E/Launcher: invoke overridePendingAppTransitionThumb failed, java.lang.NoSuchMethodException: overridePendingAppTransitionThumbFromLauncher [class android.graphics.Bitmap, int, int, boolean, boolean]
2019-07-26 12:48:34.797 3198-3198/? E/VivoSystemReflect: Failure register UserProfilingManager
    java.lang.ClassNotFoundException: com.vivo.services.userprofiling.UserProfilingManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at android.app.VivoSystemReflect.getServiceConstructor(VivoSystemReflect.java:461)
        at android.app.VivoSystemReflect.-wrap0(VivoSystemReflect.java)
        at android.app.VivoSystemReflect$6.createService(VivoSystemReflect.java:446)
        at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:858)
        at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:799)
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1518)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:659)
        at android.app.Application.getVivoUserProfilingManager(Application.java:327)
        at android.app.Activity.onResume(Activity.java:1287)
        at com.bbk.launcher2.Launcher.onResume(Launcher.java:2106)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1276)
        at android.app.Activity.performResume(Activity.java:6963)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3469)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3532)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
     Caused by: java.lang.ClassNotFoundException: com.vivo.services.userprofiling.UserProfilingManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at java.lang.Class.forName(Class.java:326) 
        at android.app.VivoSystemReflect.getServiceConstructor(VivoSystemReflect.java:461) 
        at android.app.VivoSystemReflect.-wrap0(VivoSystemReflect.java) 
        at android.app.VivoSystemReflect$6.createService(VivoSystemReflect.java:446) 
        at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:858) 
        at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:799) 
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1518) 
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:659) 
        at android.app.Application.getVivoUserProfilingManager(Application.java:327) 
        at android.app.Activity.onResume(Activity.java:1287) 
        at com.bbk.launcher2.Launcher.onResume(Launcher.java:2106) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1276) 
        at android.app.Activity.performResume(Activity.java:6963) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3469) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3532) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6211) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Yptake** [comment]
混淆的時候
-keep public class * implements com.jess.arms.integration.ConfigModule
了麽

**Comment by JessYanCoding** [comment]
目测是两个都是混淆的问题

**Comment by xilost** [comment]
> 混淆的時候
> -keep public class * implements com.jess.arms.integration.ConfigModule
> 了麽

代码都没有开启混淆。

**Comment by xilost** [comment]
> 目测是两个都是混淆的问题

目前还没启用混淆

**Comment by JessYanCoding** [comment]
那应该是 multidex 分包的问题，常见 issues 有解决方案

**Comment by huangjide** [comment]
遇到同样的问题：java.lang.NoClassDefFoundError: java.lang.invoke.SerializedLambda
debug（未开启混淆）报错，release包（开启混淆）正常。
手机5.1 参考wiki里的解决办法：
dexOptions {
     javaMaxHeapSize "4g"
     jumboMode = true
     preDexLibraries = false
     additionalParameters = [
             '--multi-dex',//多分包
             '--set-max-idx-number=60000'//每个包内方法数上限
     ]
 }

结果无效。
怎么解决debug包报错的问题呢？
