### ISSUE TITLE
升级到2.5.0后 报 Cannot fit requested classes in the main-dex file错

### ISSUE THREAD

**Issue by qrc0403** [JessYanCoding/MVPArms#319]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 2.5.2
- [x] AndroidStudio Version: v3.5.0-canary05
- [x] Gradle Plugin Version: v3.5.0-alpha05
- [x] Target Android Version: 27
- [x] Device Model: 

### Bug Description:

从2.4.1升级到2.5.0及以上都会报错，项目已经有multDex了，起初怀疑跟依赖重复有关，但是把所有依赖都隔离并且使用相同版本还是会有这个问题，所以应该是Arms内部代码升级引起的;
麻烦作者排查下，感谢！

### Related Code:
```java
  

```

### Bug Log:
```log
`
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
	at com.android.build.gradle.internal.transforms.DexMergerTransform.transform(DexMergerTransform.java:240)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
。。。。
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:37)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	... 4 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.z.a(:26)
	at com.android.tools.r8.D8.run(:9)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
	... 7 more
Caused by: com.android.tools.r8.utils.AbortException: Error: null, Cannot fit requested classes in the main-dex file (# methods: 77843 > 65536)
	at com.android.tools.r8.utils.Reporter.a(:17)
	at com.android.tools.r8.utils.Reporter.a(:6)
	at com.android.tools.r8.dex.VirtualFile.a(:26)
	at com.android.tools.r8.dex.VirtualFile$d.a(:16)
	at com.android.tools.r8.dex.ApplicationWriter.a(:9)
	at com.android.tools.r8.dex.ApplicationWriter.write(:19)
	at com.android.tools.r8.D8.d(:29)
	at com.android.tools.r8.D8.b(:1)
	at com.android.tools.r8.utils.z.a(:14)
	... 9 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForBetaSuffix'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
`

```

### Others:
隔离以来后的依赖树为：
v2.5.2
![lALPDgQ9q1zSyj5PzQGL_395_79](https://user-images.githubusercontent.com/13394690/61342874-55c79680-a87e-11e9-8f50-0fa927ec9807.png)
v2.4.1
![lALPDgQ9q1zSLc5OzQGZ_409_78](https://user-images.githubusercontent.com/13394690/61342880-5a8c4a80-a87e-11e9-9758-9bd7ab70965a.png)

**Comment by JessYanCoding** [comment]
```
Caused by: com.android.tools.r8.utils.AbortException: Error: null, Cannot fit requested classes in the main-dex file (# methods: 77843 > 65536)
	at com.android.tools.r8.utils.Reporter.a(:17)
	at com.android.tools.r8.utils.Reporter.a(:6)
	at com.android.tools.r8.dex.VirtualFile.a(:26)
	at com.android.tools.r8.dex.VirtualFile$d.a(:16)
	at com.android.tools.r8.dex.ApplicationWriter.a(:9)
	at com.android.tools.r8.dex.ApplicationWriter.write(:19)
	at com.android.tools.r8.D8.d(:29)
	at com.android.tools.r8.D8.b(:1)
	at com.android.tools.r8.utils.z.a(:14)
	... 9 more
```

**Cannot fit requested classes in the main-dex file (# methods: 77843 > 65536)**  这里意思是，你没有开启 multidex
