### ISSUE TITLE
Glide冲突问题

### ISSUE THREAD

**Issue by hardlove** [JessYanCoding/MVPArms#344]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log

 App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:341)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:333)
        at com.bumptech.glide.Glide.get(Glide.java:176)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:714)
        at com.bumptech.glide.Glide.with(Glide.java:741)
        at com.view.GlideUitls.loadGlide(GlideUitls.java:179)
        at com.view.GlideUitls.load(GlideUitls.java:38)
        at com.hardlove.wallet.utils.ImageLoadUtils.load(ImageLoadUtils.java:44)
```

### Others:
![image](https://user-images.githubusercontent.com/11812893/68734560-b4770400-0615-11ea-8e11-cf1a3d8880e8.png)
貌似新版的glide更框架中的GeneratedAppGlideModuleImpl 冲突了。

**Comment by JessYanCoding** [comment]
框架一直都有自己实现的 AppGlideModule，使用者自己不能再自己实现 AppGlideModule，需要自己通过 https://github.com/JessYanCoding/MVPArms/blob/master/arms/src/main/java/com/jess/arms/http/imageloader/glide/GlideAppliesOptions.java 进行扩展

**Comment by hardlove** [comment]
> 框架一直都有自己实现的 AppGlideModule，使用者自己不能再自己实现 AppGlideModule，需要自己通过 https://github.com/JessYanCoding/MVPArms/blob/master/arms/src/main/java/com/jess/arms/http/imageloader/glide/GlideAppliesOptions.java 进行扩展

最新版本2.5.2 还没有 /**
     * 注册{@link Glide}的组件，参考{@link com.bumptech.glide.module.LibraryGlideModule}
     *
     * @param context  Android context
     * @param glide    {@link Glide}
     * @param registry {@link Registry}
     */
    void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry); 这个方法吧 ，麻烦更新下吧

**Comment by JessYanCoding** [comment]
嗯，先源码依赖

**Comment by rexydimen** [comment]
> 嗯，先源码依赖

这个什么时候能发布啊？急等...

**Comment by hdd1024** [comment]
@hardlove  将glide版换成4.9.0或者4.8.0就好了，如果在编译的时候出现gilde包supper包的异常，就在arms项目的build.gradle依赖    api rootProject.ext.dependencies["annotations"]改成    annotationProcessor rootProject.ext.dependencies["annotations"]就可以了！

**Comment by 258188170** [comment]
什么时候解决啊

**Comment by logicsheng** [comment]
今天遇到个冲突问题，是一个aar依赖中的glide 版本和me.jessyan:arms-imageloader-glide:2.5.1  的不统一，统一之后可以了

**Comment by benben1** [comment]
这个问题啥时候修复下 目前Glide加载加密图片 与框架冲突

**Comment by wscjy** [comment]
您好，我已收到您的邮件，我会尽快给您回复。

**Comment by fqz100** [comment]
集成的其他第三库也有AppGlideModule，该怎么解决
