### ISSUE TITLE
有没有使用Fragment的源码

### ISSUE THREAD

**Issue by appsw** [JessYanCoding/MVPArms#58]
@ActivityScope
@Component(modules = UserModule.class,dependencies = AppComponent.class)
public interface UserComponent {
    void inject(UserActivity activity);
}
这个地方如果是Fragment的话是
@ActivityScope
@Component(modules = FristModule.class,dependencies = AppComponent.class)
public interface FristComponent {
    void inject(FristFragment fragment);
}的吗？

**Comment by JessYanCoding** [comment]
嗯,对的和Activity的使用没区别,就是inject 对象不一样

**Comment by huaxun66** [comment]
java.lang.RuntimeException: Failed to call observer method
        at android.arch.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:225)
        at android.arch.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193)
        at android.arch.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184)
        at android.arch.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at android.arch.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:180)
        at com.jess.arms.mvp.BasePresenter.onStart(BasePresenter.java:87)
        at com.jess.arms.mvp.BasePresenter.<init>(BasePresenter.java:64)

在fragment中inject时有报这个错，大神能帮忙看一下吗？

**Comment by JessYanCoding** [comment]
@huaxun66 报错的意思是你注解了生命周期注解的方法报错了，由于这个地方使用的是 AOP 所以框架调用你这个注解了生命周期注解的方法奔溃了，但报的是系统的错，实质问题就是你自己代码的问题，你把注解了生命周期注解的方法里的全部代码都注释了，这里就不报错了
