### ISSUE TITLE
 java.lang.NoClassDefFoundError: dagger.internal.Preconditions

### ISSUE THREAD

**Issue by wwwiiivip** [JessYanCoding/MVPArms#76]
好像是这个类涉及到android版本问题，运行环境是 4.4 模拟器

java.lang.NoClassDefFoundError: dagger.internal.Preconditions
                                                                at com.jess.arms.di.component.DaggerBaseComponent$Builder.baseModule(DaggerBaseComponent.java:60)
                                                                at com.jess.arms.base.BaseApplication.onCreate(BaseApplication.java:43)
                                                                at com.vid.ttzb.demo.app.WEApplication.onCreate(WEApplication.java:90)
                                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:136)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by JessYanCoding** [comment]
模拟器报错的可能性太多了,所以我不会解决也解决不了

**Comment by JessYanCoding** [comment]
框架最新版本已经解决了此类问题,建议更新框架

**Comment by songjian931798** [comment]
我这边也需要这个问题，更新了框架，还是没解决

**Comment by JessYanCoding** [comment]
@songjian931798 https://github.com/JessYanCoding/MVPArms/wiki/Issues#3

**Comment by songjian931798** [comment]
我就是用mvpArms的，但是更新了，所有的Component找不到符号了，明明都存在的，还有来自注释处理程序 'android.arch.lifecycle.LifecycleProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'这个错误@JessYanCoding

**Comment by JessYanCoding** [comment]
@songjian931798 在更新某个版本前, 先到 [这里](https://github.com/JessYanCoding/MVPArms/releases) 下载对应版本的 Demo,  不要改任何代码看是否能运行, 能运行说明是你自己的环境的问题, 那就自己解决
